services:
  dev:
    build:
      context: .
      target: development-dependencies-env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
